# Generated by Django 5.2.1 on 2025-08-09 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaperImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("row_count", models.IntegerField()),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arxiv_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("title", models.TextField()),
                ("abstract", models.TextField(blank=True)),
                ("authors", models.TextField(blank=True)),
                (
                    "published_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("year", models.IntegerField(blank=True, db_index=True, null=True)),
                ("month", models.CharField(blank=True, max_length=20, null=True)),
                ("categories", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("cluster", models.IntegerField(blank=True, db_index=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-published_date"],
                "indexes": [
                    models.Index(
                        fields=["cluster", "published_date"],
                        name="api_paper_cluster_a4bd49_idx",
                    ),
                    models.Index(
                        fields=["year", "month"], name="api_paper_year_4253c0_idx"
                    ),
                ],
            },
        ),
    ]
