# Generated by Django 6.0.4 on 2026-08-14 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("optional_keywords", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("papers_scanned", models.IntegerField(default=0)),
                ("papers_matched", models.IntegerField(default=0)),
                ("duplicates_skipped", models.IntegerField(default=0)),
                ("irrelevant_skipped", models.IntegerField(default=0)),
                ("topics_found", models.IntegerField(default=0)),
                ("outliers_found", models.IntegerField(default=0)),
                ("processing_seconds", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cluster_id", models.IntegerField(db_index=True)),
                ("label", models.CharField(max_length=160)),
                ("keywords", models.TextField(blank=True)),
                ("paper_count", models.IntegerField(default=0)),
                ("is_outlier", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "search_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="api.searchjob",
                    ),
                ),
            ],
            options={
                "ordering": ["is_outlier", "-paper_count", "label"],
                "unique_together": {("search_job", "cluster_id")},
            },
        ),
        migrations.CreateModel(
            name="PaperTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_assignments",
                        to="api.paper",
                    ),
                ),
                (
                    "search_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_topics",
                        to="api.searchjob",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_assignments",
                        to="api.topic",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["search_job", "confidence"],
                        name="api_paperto_search__783b06_idx",
                    ),
                    models.Index(
                        fields=["topic", "confidence"],
                        name="api_paperto_topic_i_688f73_idx",
                    ),
                ],
                "unique_together": {("paper", "search_job")},
            },
        ),
    ]
