# Generated by Django 6.0.4 on 2026-09-04 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_searchjob_topic_papertopic"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("abstract_only", "Abstract Only"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("full_text", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("extracted_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "paper",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document",
                        to="api.paper",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaperChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.IntegerField()),
                ("text", models.TextField()),
                ("embedding", models.JSONField(blank=True, default=list)),
                ("token_estimate", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="api.paper",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="api.paperdocument",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["paper", "chunk_index"],
                        name="api_paperch_paper_i_2044bd_idx",
                    )
                ],
                "unique_together": {("document", "chunk_index")},
            },
        ),
    ]
