services:
  # Frontend Service
  - type: web
    name: lite-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: PORT
        value: 10000
      - key: REACT_APP_API_URL
        value: https://lite-evolution-backend.onrender.com/api
    plan: free

  # Backend Service
  - type: web
    name: lite-backend
    env: python3
    buildCommand: |
      pip install -r backend/requirements.txt
      python backend/manage.py migrate
      python backend/manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi:application --chdir backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10001
      - key: DEBUG
        value: 'False'
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings.production
    plan: free

  # Database (if using SQLite, this is just for reference - consider using Render's PostgreSQL instead)
  # - type: postgres
  #   name: lite-db
  #   plan: free
